In [8]:
import numpy as np
#创建全为0或者全为1的数组#
t1=np.ones((2,4))
t2=np.zeros((3,4))
print(t1)
print(t2)
#创建一个对角线为1的正方形数组（方阵）#
t3=np.eye(5)
print(t3)
#获取最大值和最小值的位置#
np.argmax(t3,axis=0)
t3[t3==1]=-1#将数组中的1替换为-1
t3
np.argmin(t3,axis=1)




[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


array([0, 1, 2, 3, 4], dtype=int64)