In [35]:
#创建数组#
import numpy as np

t1= np.array([1,2,3])
print(t1)
print(type(t1))

t2= np.array(range(10))
print(t2)

t3=np.arange(10)
print(t3)
# np.array(range(x))==np.arange(10)#

t4=np.arange(4,10,2)
print(t4)
#------------------------------------------------------#

#查询数据类型：.dtype#
print(t4.dtype)

#改变数组类型#
t5=np.array(range(4,10,2), dtype="i1")
print(t5,t5.dtype)
t7=t5.astype('int64')
print(t7,t7.dtype)

#numpy中的bool类型
t6=np.array([1,1,0,0,1,0],dtype=bool)
print(t6,t6.dtype)
import random

#numpy中的小数
t8=np.array([random.random()for i in range (10)])
print(t8,t8.dtype)

t9=np.round(t8,2)#np.round的使用方法：np.round(数组，保留几位小数)#
print(t9)


[1 2 3]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[4 6 8]
int32
[4 6 8] int8
[4 6 8] int64
[ True  True False False  True False] bool
[0.91548178 0.96084136 0.98989679 0.73286178 0.71662189 0.97315716
 0.62317306 0.96119752 0.71135713 0.26432735] float64
[0.92 0.96 0.99 0.73 0.72 0.97 0.62 0.96 0.71 0.26]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01 