In [22]:
import numpy as np
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((2, 12)))
print(a)
print('---------------------------------')
t=np.hsplit(a,3)#将a数组拆成三个部分
print(t)
print('---------------------------------')
t1=np.hsplit(a, np.array([3, 7]))
t1

[[5. 9. 1. 9. 3. 4. 8. 4. 5. 0. 7. 5.]
 [3. 7. 3. 4. 1. 4. 2. 2. 7. 2. 4. 9.]]
---------------------------------
[array([[5., 9., 1., 9.],
       [3., 7., 3., 4.]]), array([[3., 4., 8., 4.],
       [1., 4., 2., 2.]]), array([[5., 0., 7., 5.],
       [7., 2., 4., 9.]])]
---------------------------------


[array([[5., 9., 1.],
        [3., 7., 3.]]),
 array([[9., 3., 4., 8.],
        [4., 1., 4., 2.]]),
 array([[4., 5., 0., 7., 5.],
        [2., 7., 2., 4., 9.]])]