In [1]:
import numpy as np
t1=np.arange(12).reshape(3,4)
#数组与单个数字的运算#
t2=t1+2
print(t2)
#同纬度数组之间的运算#
t4=t1+t2
print(t4)
#不同维度数组之间的运算
t5=np.arange(4)#一维数组加三维数组#
print(t1+t5)
print('---------------------------------')
#数组内部运算#
print(t1)
np.sum(t1)#整体求和
np.sum(t1,axis=0)#行求和，axis=1为列求和
tmean=t1.mean(axis=0)#求平均
print(tmean)
tmedian=np.median(t1,axis=1)#求中值
print(tmedian)
print('---------------------------------')
tmax=t1.max(axis=1)#求最大值
print(tmax)
tptp=np.ptp(t1,axis=0)#求极差
print(tptp)
tstd=t1.std(axis=0)#求标准差
print(tstd)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[ 0  2  4  6]
 [ 4  6  8 10]
 [ 8 10 12 14]]
---------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4. 5. 6. 7.]
[1.5 5.5 9.5]
---------------------------------
[ 3  7 11]
[8 8 8 8]
[3.26598632 3.26598632 3.26598632 3.26598632]
