In [14]:
import numpy as np
t1=np.arange(24).reshape(4,6)
print(t1)
print("------------------------")
#将t1中小于10的值替换为5#
t1[t1<10]=5
print(t1)
print("------------------------")
#使用np.where#
t2=np.where(t1<10,0,10)
print(t2)
print("------------------------")
#使用.clip#
t3=t1.clip(10,20)
print(t3)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
------------------------
[[ 5  5  5  5  5  5]
 [ 5  5  5  5 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
------------------------
[[ 0  0  0  0  0  0]
 [ 0  0  0  0 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
------------------------
[[10 10 10 10 10 10]
 [10 10 10 10 10 11]
 [12 13 14 15 16 17]
 [18 19 20 20 20 20]]
