In [6]:
import numpy as np
t1=np.arange(12).reshape(2,6)
t2=np.arange(12,24).reshape(2,6)
print(t1)
print(t2)
print('---------------------------------')
#行交换#
t1[[0,1],:]=t1[[1,0],:]
print(t1)
#列交换#
t2[:,[0,2]]=t2[:,[2,0]]
print(t2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
---------------------------------
[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]]
[[14 13 12 15 16 17]
 [20 19 18 21 22 23]]
