In [11]:
import numpy as np
t1=np.arange(24).reshape(6,4)
print(t1)
print("------------------------")
#取行#
print(t1[2])
print("------------------------")
#连续取行#
print(t1[2:])
print('------------------------')
#取不连续的行#
print(t1[[1,3,5]])
print('------------------------')
#取列#
print(t1[:,0])
print('------------------------')
#连续取列#
print(t1[:,2:])
print('------------------------')
#取不连续多列#
print(t1[:,[0,2]])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
------------------------
[ 8  9 10 11]
------------------------
[[ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
------------------------
[[ 4  5  6  7]
 [12 13 14 15]
 [20 21 22 23]]
------------------------
[ 0  4  8 12 16 20]
------------------------
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]]
------------------------
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]
 [16 18]
 [20 22]]
