In [19]:
import numpy as np
# .shape 展示数组是几维数组 #
t1=np.arange(12)
print(t1,t1.shape)

t2=np.array([[1,2,3],[4,5,6]])
print(t2,t2.shape)

t3=np.array([[[1,2,3],[4,5,6]],[[6,5,4],[219,23,1]]])
print(t3,t3.shape)

#改变数组维数#
t4=np.arange(36)
t5=t4.reshape((4,9))#从1维改成2维#
print(t5)
t6=t4.reshape((2,3,6))#1维改成3维#
print(t6)

#.flatten的使用将其将为一维数组#
print(t6.flatten())




[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[1 2 3]
 [4 5 6]] (2, 3)
[[[  1   2   3]
  [  4   5   6]]

 [[  6   5   4]
  [219  23   1]]] (2, 2, 3)
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [27 28 29 30 31 32 33 34 35]]
[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
