In [6]:
import numpy as np
a = np.arange(12)**2 
i = np.array([1, 1, 3, 8, 5])
print(a)
print(i)
t=a[i]#在i位置上的a值#
print(t)
j = np.array([[3, 4], [9, 7]])
a[j]

[  0   1   4   9  16  25  36  49  64  81 100 121]
[1 1 3 8 5]
[ 1  1  9 64 25]


array([[ 9, 16],
       [81, 49]])