In [9]:
import numpy as np
t1=np.arange(12).reshape(2,6)
t2=np.arange(12,24).reshape(2,6)
print(t1)
print(t2)
print('---------------------------------')
#竖直拼接：np.vstack((t1,t2))#
np.vstack((t1,t2))
print('---------------------------------')
#水平拼接：np.hstack((t1,t2))#
np.hstack((t1,t2))


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
---------------------------------
---------------------------------


array([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23]])